# -*- coding: utf-8 -*-
"""Superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfVwkcGyS0aEl2mO0G1Yne-n3lb9uC-Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Sample - Superstore.csv", encoding='latin1')

df.head(5)

df.info()

df.describe()

df.drop_duplicates(inplace=True)

df.info()

grouped=df.groupby('Segment')[['Profit','Sales']].sum()
grouped['Sales - Profit'] = grouped['Sales'] - grouped['Profit']
grouped.style.format('{:,.2f}')

x=grouped.index
y=grouped['Profit']
plt.bar(x,y)
plt.xlabel('Segment')
plt.ylabel('Profit')
plt.title('Profit by Segment')
plt.show()

"""***Analysis of profit distribution reveals that the Consumer segment outperforms both Corporate and Home Office. This suggests that the majority of our successful business transactions are coming from individual end-consumers.***"""

grouped_order = df.groupby('Segment')['Quantity'].apply(lambda x: x.mode().iloc[0])
print(grouped_order)

grouped_cust =df.groupby('Customer ID')['Customer ID'].count()
cust_state = grouped_cust.apply(lambda x: 'Bronze' if x < 5 else ('Silver' if x <= 10 else ('Gold' if x<=20 else 'Platinum')))
grouped_state = cust_state.value_counts()
print(grouped_state)

x= grouped_state.index
y= grouped_state
colors = ['#FFD700', '#C0C0C0', '#E5E4E2', '#CD7F32']
plt.pie(y, labels=x, autopct='%1.1f%%', colors=colors, startangle=140)

plt. title('Customer state distribution')
plt.show()

"""-The store has a good retention rate, as the number of Gold and Platinum customers is quite high.

-Customers tend to buy three items per order. We can use this insight to offer discounts for customers who purchase three or more items.


"""

groupcat=df.groupby('Category')['Profit'].sum()
print(groupcat.sort_values(ascending=False))

x=groupcat.index
y=groupcat
plt.bar(x,y)
plt.xlabel('Category')
plt.ylabel('Profit')
plt.title('profit of each category')
plt.show()

gropreg= df.groupby('Region')['Profit'].sum()
print(gropreg.sort_values(ascending=False))

df[['Discount','Profit','Sales']].corr()

sns.heatmap(df[['Discount','Profit','Sales']].corr(),annot=True)

"""Discounts do not have a significant impact on Sales; in other words, they do not drive volume. However, they clearly decrease the overall Profit."""

df['Order Date']= pd.to_datetime(df['Order Date'],format='%m/%d/%Y')
yearly_profit= df.groupby(df['Order Date'].dt.year)[['Profit','Discount']].sum()
print(yearly_profit)
sns.lineplot(x=yearly_profit.index,y=yearly_profit['Profit'])
plt.xlabel('Year')
plt.ylabel('Profit')
plt.title('Yearly Profit Trend')
plt.grid(True)
plt.xticks(yearly_profit.index)
plt.show()

df['Order Date']= pd.to_datetime(df['Order Date'],format='%m/%d/%Y')
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month

yearly_monthly_profit = df.groupby(['Year', 'Month'])['Profit'].sum().reset_index()

sns.lineplot(data=yearly_monthly_profit, x='Month', y='Profit', hue='Year', marker='o')
plt.xlabel('Month')
plt.ylabel('Profit')
plt.title('Monthly Profit Trend by Year')
plt.grid(True)
plt.xticks(range(1, 13)) # Ensure all month labels (1-12) are shown
plt.legend(title='Year')
plt.show()

"""-the store grows at steady pace, so the profit is increasing within the years


"""

df['Ship Date'] = pd.to_datetime(df['Ship Date'],format='%m/%d/%Y')
df['shiping time']= df['Ship Date']-df['Order Date']

# Calculate mode
groupship_mode = df.groupby('Category')['shiping time'].apply(lambda x: x.mode().iloc[0])
print("Mode of shipping time by Category:\n", groupship_mode)

# Calculate mean
groupship_mean = df.groupby('Category')['shiping time'].mean()
print("\nMean of shipping time by Category:\n", groupship_mean)

# Calculate max
groupship_max = df.groupby('Category')['shiping time'].max()
print("\nMax shipping time by Category:\n", groupship_max)

"""# **📊 Executive Summary & Key Insights**

1- **Product Performance:** Technology is the primary profit driver (Top
Performer), followed by Office Supplies. Furniture shows a significant drop in profitability.

2-**Customer Segments:** The Consumer segment leads in both order volume and profit. All segments (Consumer, Corporate, and Home Office) maintain healthy performance levels.

3- **Regional Growth:** The West region is the most profitable, with the East region following as a strong second.

4- **Trend & Seasonality:** There is no clear seasonality pattern over the 4-year period. Business growth depends on individual large deals rather than specific times of the year.

5- **Discount Strategy:** The current discount system is inefficient; it has a weak impact on sales volume and a negative correlation with profit margins.

6- **Purchase Behavior:** Most customers tend to buy 3 items per order.

7- **Overall Growth:** The store has demonstrated a steady and consistent growth pace throughout the 4-year duration.

# 💡 Strategic Recommendations

Dynamic Discounting: Implement targeted discounts for customers buying 3 or more items to increase the Average Order Value (AOV).

Focus on High-Margin Categories: Allocate more marketing resources toward Technology and Office Supplies to maximize ROI.

Loyalty Program (VIP Treatment): Leverage the high retention rate by offering exclusive benefits to Golden and Silver customers. Create a "Pathway" marketing plan to incentivize Bronze customers to upgrade to VIP status.

Data-Driven Promotions: Since there is no seasonality, use "Artificial Peaks" (like Flash Sales) during low-performance months to stabilize revenue.
"""